### ISSUE TITLE
_slug parameters instead of _id

### ISSUE THREAD

**Issue by psychoche** [motdotla/digitalocean#46]
Hello!

How can I get _slug parameters instead of _id parameters?
For example: I need name of image not just it's id. 
As I see in DO V1 API documentation it's possible. But how can I do it with this gem?

Thank you in advance.

**Comment by motdotla** [comment]
Hi @psychoche were you able to end up solving this? If not I recommend DigitalOcean's Official rubygem: https://github.com/digitalocean/droplet_kit
