### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by merqlove** [motdotla/digitalocean#50]
Hello, I think new release needed, because of updated dependencies in gemspec.
I'm really waiting for it.

**Comment by motdotla** [comment]
Hi @merqlove: I decided not to since I gave this repo no love. Instead it will just stay at V1 and I've added a notice here [1] for using the v2 gem.

[1] https://github.com/motdotla/digitalocean#the-easiest-and-most-complete-rubygem-for-digitalocean

**Comment by merqlove** [comment]
@motdotla Yeah, soon this gem will be unneeded. Due DO API V1 deprecation.
